profiles:
  - name: safeBiking
    vehicle: bike
    weighting: custom
    custom_model: {
        "priority": [{
          "if": "max_speed >= 50",
          "multiply_by": "0.1"
        }, {
          "if": "bike_network == MISSING",
          "multiply_by": "0.9"
        }]            
    }       